In [17]:
# Exercise 1 : Array Creation and Manipulation
import numpy as np
array_1d = np.array([0,1,2,3,4,5,6,7,8,9])
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#Exercise 2 : Type Conversion and Array Operations
list1 = [3.14,2.17,0,1,2]
array2 = np.array(list1)
array2 = array2.astype(int)
array2

array([3, 2, 0, 1, 2])

In [21]:
# Exercise 3 : Working with Multi-Dimensional Arrays
array3x3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
#  Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
array_floats = np.random.rand(4,5)
array_floats = np.around(array_floats,2)
array_floats

array([[0.42, 0.54, 0.72, 0.75, 0.15],
       [0.96, 0.9 , 0.65, 0.54, 0.53],
       [0.55, 0.01, 0.11, 0.05, 0.53],
       [0.29, 0.76, 0.02, 0.05, 0.96]])

In [35]:
# Exercise 5 : Indexing Arrays
array_floats[1] #selecting 2nd row

array([0.96, 0.9 , 0.65, 0.54, 0.53])

In [36]:
# Exercise 6 : Reversing elements
array_3 = np.array([0,1,2,3,4,5,6,7,8,9])
new_array = array_3[::-1]
new_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [42]:
# Exercise 7 : Identity Matrix
matrix_array = np.identity(4)
matrix_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
# Exercise 8 : Simple Aggregate Funcs
print(f'Sum:{array_3.sum()}, Average: {array_3.mean()}')

Sum:45, Average: 4.5


In [55]:
#Exercise 9 : Create Array and Change its Structure
array_20 = np.arange(1,21)
array_20.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [56]:
# Exercise 10 : Conditional Selection of Values
array_3[array_3%2==1]

array([1, 3, 5, 7, 9])

In [57]:
array_3[array_3%2==0]

array([0, 2, 4, 6, 8])